apiVersion: v1
kind: Namespace
metadata:
  name: ai-content-factory
  labels:
    app: ai-content-factory
    version: v1.0.0
    environment: production
  annotations:
    description: "AI Content Factory - Automated content creation and distribution system"
    contact: "devops@ai-content-factory.com"
    created-by: "AI Content Factory DevOps Team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-content-factory-quota
  namespace: ai-content-factory
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-content-factory-limits
  namespace: ai-content-factory
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "4Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-content-factory-network-policy
  namespace: ai-content-factory
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ai-content-factory
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - {}  # Allow all egress traffic